package com.xszj.mba.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xszj.mba.bean.AnswerBean;
import com.xszj.mba.bean.QuestionBean;

import com.xszj.mba.bean.AnswerBeanDao;
import com.xszj.mba.bean.QuestionBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerBeanDaoConfig;
    private final DaoConfig questionBeanDaoConfig;

    private final AnswerBeanDao answerBeanDao;
    private final QuestionBeanDao questionBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerBeanDaoConfig = daoConfigMap.get(AnswerBeanDao.class).clone();
        answerBeanDaoConfig.initIdentityScope(type);

        questionBeanDaoConfig = daoConfigMap.get(QuestionBeanDao.class).clone();
        questionBeanDaoConfig.initIdentityScope(type);

        answerBeanDao = new AnswerBeanDao(answerBeanDaoConfig, this);
        questionBeanDao = new QuestionBeanDao(questionBeanDaoConfig, this);

        registerDao(AnswerBean.class, answerBeanDao);
        registerDao(QuestionBean.class, questionBeanDao);
    }
    
    public void clear() {
        answerBeanDaoConfig.clearIdentityScope();
        questionBeanDaoConfig.clearIdentityScope();
    }

    public AnswerBeanDao getAnswerBeanDao() {
        return answerBeanDao;
    }

    public QuestionBeanDao getQuestionBeanDao() {
        return questionBeanDao;
    }

}
